#+TODO: APPT RESCHEDULE | DONE CANCELED
#+TODO: FEAST SOLEMENITY | OBSERVED
#+TODO: | REMOVED
* Special Dates
** Birthdays
** Anniversaries
** Holidays

* Appointments
** 2020
*** August
**** DONE Belmont Dentistry
     - Note taken on [2020-08-31 Mon 14:19] \\
       - Dentist visit went well. My lower left molar is missing. I am not sure it was ever there.  Was seen by Dr. Sandhu's wife (also Dr. Sandhu) for the first time. She recommomended another implant since my upper left molar is coming down out of the bone/gum since there is not another tooth working to keep it in place. 
       - Took CT scan to see if there was enough bone to do the implant in the first place.
<2020-08-31 Mon 08:00>
*** November
**** APPT Belmont Dentistry
   SCHEDULED:<2020-11-30 Mon 10:00--11:00>
 Dental Cleaning 
 :LOGBOOK:
   - Added: [2020-08-31 Mon 15:23]
   :END:
** 2020-08 August
*** 2020-08-31 Monday
** 2020-09 September
*** 2020-09-03 Thursday
**** APPT Life Giving Wounds: Retreat For Children of Divorce
     SCHEDULED:<2020-10-01 Thu 17:36--2020-11-12>
   Online Retreat for children of divorced parents. Thursday evenings. 
   :LOGBOOK:
     - Added: [2020-09-03 Thu 17:36]
     :END: 
* Inbox


