* My Performance
** Reviews
*** Coaching
**** Sr. TSS Kassandra
**** [2020-09-10 Thu] 
Feedback: I was live monitoring you today to help with CPH, out of the 3 calls I listen to I have found 2 areas we can work on together to increase the CPH. The first area of focus for us is to be confident.  We should remain confident in what we are telling the customer, remember we are the expert. When we say Let me ask or Hold on just a minute it sounds like we are not knowledgeable, this makes our calls long and can affect our VOC. What we can try instead is saying Let me check my resources or Let me research that for you. Another area of focus would be to Empathetic responses. Be empathetic but continue to move on. Something that can help is AIQ, Acknowledge, Inform, Question. This will also help us in call control by dong this we are acknowledging their comments, but also staying on topic. Eric provided a sheet to refer to with empathetic responses to help with this also. Here is a specific example, customer says My phone is not working an empathetic AIQ response would be:  I completely understand your frustration I would feel the same if my phone wasnt working. I would be happy to help you fix your phone, what error message are you receiving? By doing this you are being empathetic, setting the tone and flow for the call, and giving an assurance of help. After this each time they comment on something have an empathetic response ready. Another specific example would be, customer says 'I just dont understand how to do this. An empathetic response would be I understand this is tedious and frustrating, I have been there too, You are doing great! Describe to me what is on the screen please. By asking them to describe what is on the screen we will be able to learn their lingo. This will help us throughout the entire call because they will be able to understand the directions we are giving them. This will also help us stay on topic and get through the call faster so our CPH will increase.
*** Supervisor Eric Branham
**** [2020-09-10 Thu]
(12:16) Travis Arnold: I think ive improved since last month at least  though
(12:23) Eric Branham: You have made HUGE improvments this last month and since cominig to the team that's why I gave you that shout out this morning in rally!  
You're doing a good job and you listen to the feedback and tips we give you and you apply it right away to your next call. 
If I go over something with you I know you won't have an issue with it again and you will be able to do it on your own going forward. 
You're a great agent Travis.  Don't doubt yourself!! 
**** [2020-09-23 Wed]
- /Good Progress/
  - Frequency of reaching out is down.
  - Successfully implementing coaching
  - CPH currently down, but trending towards meeting standard.
- Passed Call today, was feedback
  - Great tone w/ empathy statement
  - No dead air on that call
- Things to do differently: 
  - Reassure customer nothing looks out of place on account.
  - Be more explicit that I do not notice anything wrong.
  - Limit calls to just the issue they ask about.


** Call Grading
** Conversations
*** Wiley F
**** [2020-01-09] Efficiency and que time.
- I asked a question regarding my last call: over 1 hour. Wiley asked if there was usage on account, I wasn't sure. IE if usage why was a second SIM activating: problem with device or maybe network not the SIM card.
- Brief conversation about lollygagging during calls, dragging calls out and why that happens. If agents think that available time exists, then they end calls quicker, overall more productive.
- Discussed notes on calls and formatting.
  - Wiley did not use format, preferred one line  to enter information.
** Success
*** Met Bonus Requirements EOM August 202
*** Met Bonus Requirements for December 2020, January 2021.
*** /PROMOTION/ to TSS 8 Feb. 2021, pay raise. Restructure of bonus and flat payraise also occured 1 week later.

** Training
Giving feedback to new hires during training. First week feedback should be targeted to how comfortable they feel on the phones, look for the required verbiage. Week 2 can begin adjusting metrics.
| Week              | Metric                                                                                                                                                         |
|-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Beginning Week    | 2 Comfortable on the phone, Do they sound confident, excited  Mandatory Verbiage, ACW                                                                          |
| Middle/End Week 2 | Hold times/mute/: How does that impact cust. experience, How does ACW impact you, Identify Agents needing extra help Implent goals: reduce hold/ACW: 1/3, 50 % |
| Week 3            | Continue to review calls, provide feedback, Target feedback around goals.                                                                                      |


